// Complete CARC (Claim Adjustment Reason Codes) and RARC (Remittance Advice Remark Codes) database
// Sources: WPC (Washington Publishing Company) official list, CMS, medibillmd.com

export interface DenialCodeSeed {
  code: string;
  codeType: 'CARC' | 'RARC';
  description: string;
  category: string;
}

export const ALL_DENIAL_CODES: DenialCodeSeed[] = [
  // ==================== CARC CODES ====================
  { code: '1', codeType: 'CARC', description: 'Deductible Amount', category: 'Patient Responsibility' },
  { code: '2', codeType: 'CARC', description: 'Coinsurance Amount', category: 'Patient Responsibility' },
  { code: '3', codeType: 'CARC', description: 'Co-payment Amount', category: 'Patient Responsibility' },
  { code: '4', codeType: 'CARC', description: 'The procedure code is inconsistent with the modifier used or a required modifier is missing', category: 'Coding' },
  { code: '5', codeType: 'CARC', description: 'The procedure code/type of bill is inconsistent with the place of service', category: 'Coding' },
  { code: '6', codeType: 'CARC', description: 'The procedure/revenue code is inconsistent with the patient\'s age', category: 'Coding' },
  { code: '7', codeType: 'CARC', description: 'The procedure/revenue code is inconsistent with the patient\'s gender', category: 'Coding' },
  { code: '8', codeType: 'CARC', description: 'The procedure code is inconsistent with the provider type/specialty (taxonomy)', category: 'Provider' },
  { code: '9', codeType: 'CARC', description: 'The diagnosis is inconsistent with the patient\'s age', category: 'Coding' },
  { code: '10', codeType: 'CARC', description: 'The diagnosis is inconsistent with the patient\'s gender', category: 'Coding' },
  { code: '11', codeType: 'CARC', description: 'The diagnosis is inconsistent with the procedure', category: 'Coding' },
  { code: '12', codeType: 'CARC', description: 'The diagnosis is inconsistent with the provider type', category: 'Coding' },
  { code: '13', codeType: 'CARC', description: 'The date of death precedes the date of service', category: 'Eligibility' },
  { code: '14', codeType: 'CARC', description: 'The date of birth follows the date of service', category: 'Eligibility' },
  { code: '15', codeType: 'CARC', description: 'The authorization number is missing, invalid, or does not apply to the billed services or provider', category: 'Authorization' },
  { code: '16', codeType: 'CARC', description: 'Claim/service lacks information or has submission/billing error(s)', category: 'Documentation' },
  { code: '17', codeType: 'CARC', description: 'Requested information was not provided or was insufficient/incomplete', category: 'Documentation' },
  { code: '18', codeType: 'CARC', description: 'Exact duplicate claim/service', category: 'Duplicate' },
  { code: '19', codeType: 'CARC', description: 'This is a work-related injury/illness and thus the liability of the Worker\'s Compensation Carrier', category: 'Liability' },
  { code: '20', codeType: 'CARC', description: 'This injury/illness is covered by the liability carrier', category: 'Liability' },
  { code: '21', codeType: 'CARC', description: 'This injury/illness is the liability of the no-fault carrier', category: 'Liability' },
  { code: '22', codeType: 'CARC', description: 'This care may be covered by another payer per coordination of benefits', category: 'Coordination of Benefits' },
  { code: '23', codeType: 'CARC', description: 'The impact of prior payer(s) adjudication including payments and/or adjustments', category: 'Coordination of Benefits' },
  { code: '24', codeType: 'CARC', description: 'Charges are covered under a capitation agreement/managed care plan', category: 'Managed Care' },
  { code: '26', codeType: 'CARC', description: 'Expenses incurred prior to coverage', category: 'Coverage' },
  { code: '27', codeType: 'CARC', description: 'Expenses incurred after coverage terminated', category: 'Coverage' },
  { code: '29', codeType: 'CARC', description: 'The time limit for filing has expired', category: 'Timely Filing' },
  { code: '31', codeType: 'CARC', description: 'Patient cannot be identified as our insured', category: 'Eligibility' },
  { code: '32', codeType: 'CARC', description: 'Our records indicate the patient is not an eligible dependent', category: 'Eligibility' },
  { code: '33', codeType: 'CARC', description: 'Insured has no dependent coverage', category: 'Eligibility' },
  { code: '34', codeType: 'CARC', description: 'Insured has no coverage for newborns', category: 'Eligibility' },
  { code: '35', codeType: 'CARC', description: 'Lifetime benefit maximum has been reached', category: 'Benefit Limit' },
  { code: '39', codeType: 'CARC', description: 'Services denied at the time authorization/pre-certification was requested', category: 'Authorization' },
  { code: '40', codeType: 'CARC', description: 'Charges do not meet qualifications for emergent/urgent care', category: 'Medical Necessity' },
  { code: '44', codeType: 'CARC', description: 'Prompt-pay discount', category: 'Contractual' },
  { code: '45', codeType: 'CARC', description: 'Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement', category: 'Fee Schedule' },
  { code: '49', codeType: 'CARC', description: 'This is a non-covered service because it is a routine/preventive exam or a diagnostic/screening procedure done in conjunction with a routine/preventive exam', category: 'Non-Covered' },
  { code: '50', codeType: 'CARC', description: 'These are non-covered services because this is not deemed a \'medical necessity\' by the payer', category: 'Medical Necessity' },
  { code: '51', codeType: 'CARC', description: 'These are non-covered services because this is a pre-existing condition', category: 'Non-Covered' },
  { code: '53', codeType: 'CARC', description: 'Services by an immediate relative or a member of the same household are not covered', category: 'Non-Covered' },
  { code: '54', codeType: 'CARC', description: 'Multiple physicians/assistants are not covered in this case', category: 'Non-Covered' },
  { code: '55', codeType: 'CARC', description: 'Procedure/treatment/drug is deemed experimental/investigational by the payer', category: 'Non-Covered' },
  { code: '56', codeType: 'CARC', description: 'Procedure/treatment has not been deemed \'proven to be effective\' by the payer', category: 'Non-Covered' },
  { code: '57', codeType: 'CARC', description: 'Payment denied/reduced because the payer deems the information submitted does not support this level of service, this many services, this length of service, or this dosage', category: 'Medical Necessity' },
  { code: '58', codeType: 'CARC', description: 'Treatment was deemed by the payer to have been rendered in an inappropriate or invalid place of service', category: 'Place of Service' },
  { code: '59', codeType: 'CARC', description: 'Processed based on multiple or concurrent procedure rules (e.g. multiple surgeries, diagnostic imaging, concurrent anesthesia)', category: 'Bundling' },
  { code: '60', codeType: 'CARC', description: 'Charges for outpatient services are not covered when performed within a period of time prior to or after inpatient services', category: 'Non-Covered' },
  { code: '61', codeType: 'CARC', description: 'Adjusted for failure to obtain second surgical opinion', category: 'Authorization' },
  { code: '66', codeType: 'CARC', description: 'Blood Deductible', category: 'Patient Responsibility' },
  { code: '69', codeType: 'CARC', description: 'Day outlier amount', category: 'Contractual' },
  { code: '70', codeType: 'CARC', description: 'Cost outlier - Adjustment to compensate for additional costs', category: 'Contractual' },
  { code: '74', codeType: 'CARC', description: 'Indirect Medical Education Adjustment', category: 'Contractual' },
  { code: '75', codeType: 'CARC', description: 'Direct Medical Education Adjustment', category: 'Contractual' },
  { code: '76', codeType: 'CARC', description: 'Disproportionate Share Adjustment', category: 'Contractual' },
  { code: '78', codeType: 'CARC', description: 'Non-Covered days/Room charge adjustment', category: 'Non-Covered' },
  { code: '85', codeType: 'CARC', description: 'Patient Interest Adjustment', category: 'Patient Responsibility' },
  { code: '89', codeType: 'CARC', description: 'Professional fees removed from charges', category: 'Contractual' },
  { code: '90', codeType: 'CARC', description: 'Ingredient cost adjustment (pharmaceuticals only)', category: 'Contractual' },
  { code: '91', codeType: 'CARC', description: 'Dispensing fee adjustment', category: 'Contractual' },
  { code: '94', codeType: 'CARC', description: 'Processed in Excess of charges', category: 'Contractual' },
  { code: '95', codeType: 'CARC', description: 'Plan procedures not followed', category: 'Authorization' },
  { code: '96', codeType: 'CARC', description: 'Non-covered charge(s). At least one Remark Code must be provided', category: 'Non-Covered' },
  { code: '97', codeType: 'CARC', description: 'The benefit for this service is included in the payment/allowance for another service/procedure that has already been adjudicated', category: 'Bundling' },
  { code: '100', codeType: 'CARC', description: 'Payment made to patient/insured/responsible party', category: 'Payment' },
  { code: '101', codeType: 'CARC', description: 'Predetermination: anticipated payment upon completion of services or claim adjudication', category: 'Contractual' },
  { code: '102', codeType: 'CARC', description: 'Major Medical Adjustment', category: 'Contractual' },
  { code: '103', codeType: 'CARC', description: 'Provider promotional discount (e.g. Senior citizen discount)', category: 'Contractual' },
  { code: '104', codeType: 'CARC', description: 'Managed care withholding', category: 'Managed Care' },
  { code: '105', codeType: 'CARC', description: 'Tax withholding', category: 'Contractual' },
  { code: '106', codeType: 'CARC', description: 'Patient payment option/election not in effect', category: 'Patient Responsibility' },
  { code: '107', codeType: 'CARC', description: 'The related or qualifying claim/service was not identified on this claim', category: 'Documentation' },
  { code: '108', codeType: 'CARC', description: 'Rent/purchase guidelines were not met', category: 'Non-Covered' },
  { code: '109', codeType: 'CARC', description: 'Claim/service not covered by this payer/contractor. You must send the claim/service to the correct payer/contractor', category: 'Coverage' },
  { code: '110', codeType: 'CARC', description: 'Billing data file not available', category: 'Documentation' },
  { code: '111', codeType: 'CARC', description: 'Not covered unless the provider accepts assignment', category: 'Provider' },
  { code: '112', codeType: 'CARC', description: 'Service not furnished directly to the patient and/or not documented', category: 'Documentation' },
  { code: '114', codeType: 'CARC', description: 'Procedure/product not approved by the Food and Drug Administration', category: 'Non-Covered' },
  { code: '115', codeType: 'CARC', description: 'Procedure postponed, canceled, or delayed', category: 'Non-Covered' },
  { code: '116', codeType: 'CARC', description: 'The advance indemnity notice signed by the patient did not comply with requirements', category: 'Documentation' },
  { code: '117', codeType: 'CARC', description: 'Transportation is only covered to the closest facility that can provide the necessary care', category: 'Non-Covered' },
  { code: '118', codeType: 'CARC', description: 'ESRD network support adjustment', category: 'Contractual' },
  { code: '119', codeType: 'CARC', description: 'Benefit maximum for this time period or occurrence has been reached', category: 'Benefit Limit' },
  { code: '120', codeType: 'CARC', description: 'Patient is covered by a managed care plan', category: 'Managed Care' },
  { code: '121', codeType: 'CARC', description: 'Indemnification adjustment - Loss Allocations', category: 'Contractual' },
  { code: '122', codeType: 'CARC', description: 'Psychiatric reduction', category: 'Contractual' },
  { code: '125', codeType: 'CARC', description: 'Submission/billing error(s). At least one Remark Code must be provided', category: 'Documentation' },
  { code: '127', codeType: 'CARC', description: 'Coinsurance', category: 'Patient Responsibility' },
  { code: '128', codeType: 'CARC', description: 'Newborn\'s services are covered in the mother\'s Allowance', category: 'Bundling' },
  { code: '129', codeType: 'CARC', description: 'Prior processing information', category: 'Contractual' },
  { code: '130', codeType: 'CARC', description: 'Claim submission fee', category: 'Contractual' },
  { code: '131', codeType: 'CARC', description: 'Claim specific negotiated discount', category: 'Contractual' },
  { code: '132', codeType: 'CARC', description: 'Prescheduled/Rescheduled Reduction', category: 'Contractual' },
  { code: '133', codeType: 'CARC', description: 'The disposition of this claim/service is pending further review', category: 'Pending' },
  { code: '134', codeType: 'CARC', description: 'Technical fees removed from claim/service or included in the allowance for another service/procedure', category: 'Bundling' },
  { code: '135', codeType: 'CARC', description: 'Claim delayed for review', category: 'Pending' },
  { code: '136', codeType: 'CARC', description: 'Failure to follow prior payer\'s coverage rules', category: 'Coordination of Benefits' },
  { code: '137', codeType: 'CARC', description: 'Regulatory Surcharges, Assessments, Allowances or Health Related Tax', category: 'Contractual' },
  { code: '138', codeType: 'CARC', description: 'Appeal procedures not followed or time limits not met', category: 'Timely Filing' },
  { code: '139', codeType: 'CARC', description: 'Contracted rate expired', category: 'Contractual' },
  { code: '140', codeType: 'CARC', description: 'Patient/Insured health identification number and name do not match', category: 'Eligibility' },
  { code: '141', codeType: 'CARC', description: 'Claim spans eligible and ineligible periods of coverage', category: 'Coverage' },
  { code: '142', codeType: 'CARC', description: 'Monthly Medicaid patient liability amount', category: 'Patient Responsibility' },
  { code: '143', codeType: 'CARC', description: 'Portion of payment deferred', category: 'Contractual' },
  { code: '144', codeType: 'CARC', description: 'Incentive adjustment, e.g. preferred product/service', category: 'Contractual' },
  { code: '146', codeType: 'CARC', description: 'Diagnosis was invalid for the date(s) of service reported', category: 'Coding' },
  { code: '147', codeType: 'CARC', description: 'Provider contracted/negotiated rate expired or not on file', category: 'Contractual' },
  { code: '148', codeType: 'CARC', description: 'Information from another provider was not provided or was insufficient/incomplete', category: 'Documentation' },
  { code: '149', codeType: 'CARC', description: 'Lifetime benefit maximum has been reached for this service/benefit category', category: 'Benefit Limit' },
  { code: '150', codeType: 'CARC', description: 'Payer deems the information submitted does not support this level of service', category: 'Medical Necessity' },
  { code: '151', codeType: 'CARC', description: 'Payment adjusted because the payer deems the information submitted does not support this many/frequency of services', category: 'Medical Necessity' },
  { code: '152', codeType: 'CARC', description: 'Payer deems the information submitted does not support this length of service', category: 'Medical Necessity' },
  { code: '153', codeType: 'CARC', description: 'Payer deems the information submitted does not support this dosage', category: 'Medical Necessity' },
  { code: '154', codeType: 'CARC', description: 'Patient is not eligible for the benefit for the date(s) of service', category: 'Eligibility' },
  { code: '157', codeType: 'CARC', description: 'Service/procedure denied based on the review of attached documentation', category: 'Medical Necessity' },
  { code: '160', codeType: 'CARC', description: 'Injury/illness was caused by an accident for which benefits are available through other sources', category: 'Liability' },
  { code: '163', codeType: 'CARC', description: 'Discount agreed to in Preferred Provider contract', category: 'Contractual' },
  { code: '164', codeType: 'CARC', description: 'Penalty for failure to obtain pre-certification/authorization', category: 'Authorization' },
  { code: '167', codeType: 'CARC', description: 'This (these) diagnosis(es) is (are) not covered', category: 'Non-Covered' },
  { code: '169', codeType: 'CARC', description: 'Alternate benefit has been provided', category: 'Contractual' },
  { code: '170', codeType: 'CARC', description: 'Payment is denied when performed/billed by this type of provider', category: 'Provider' },
  { code: '171', codeType: 'CARC', description: 'Payment is denied when performed/billed by this type of provider in this type of facility', category: 'Provider' },
  { code: '172', codeType: 'CARC', description: 'Payment is adjusted when performed/billed by a provider of this specialty', category: 'Provider' },
  { code: '173', codeType: 'CARC', description: 'Service/equipment/drug is not covered under the patient\'s current benefit plan', category: 'Non-Covered' },
  { code: '174', codeType: 'CARC', description: 'Service was not prescribed by a physician', category: 'Authorization' },
  { code: '175', codeType: 'CARC', description: 'Prescription drug is not covered/approved by formulary', category: 'Non-Covered' },
  { code: '176', codeType: 'CARC', description: 'Reduced payment per clinical trial guidelines', category: 'Contractual' },
  { code: '177', codeType: 'CARC', description: 'Patient has not met the required eligibility requirements', category: 'Eligibility' },
  { code: '178', codeType: 'CARC', description: 'Non-covered services rendered during a demonstration project', category: 'Non-Covered' },
  { code: '179', codeType: 'CARC', description: 'Services not provided or authorized by designated (network/primary care) providers', category: 'Provider' },
  { code: '180', codeType: 'CARC', description: 'Service furnished in a hospital or non-network ambulatory surgical center', category: 'Provider' },
  { code: '181', codeType: 'CARC', description: 'Procedure code was invalid on the date of service', category: 'Coding' },
  { code: '182', codeType: 'CARC', description: 'Procedure modifier was invalid on the date of service', category: 'Coding' },
  { code: '183', codeType: 'CARC', description: 'The referring provider is not eligible to refer the service billed', category: 'Provider' },
  { code: '184', codeType: 'CARC', description: 'The prescribing/ordering provider is not eligible to prescribe/order the service billed', category: 'Provider' },
  { code: '185', codeType: 'CARC', description: 'The rendering provider is not eligible to perform the service billed', category: 'Provider' },
  { code: '186', codeType: 'CARC', description: 'Level of care change adjustment', category: 'Contractual' },
  { code: '187', codeType: 'CARC', description: 'Consumer Spending Account payments (includes but is not limited to Flexible Spending Account, Health Savings Account, Health Reimbursement Account, etc.)', category: 'Payment' },
  { code: '188', codeType: 'CARC', description: 'This product/procedure is only covered when used according to FDA recommendations', category: 'Non-Covered' },
  { code: '189', codeType: 'CARC', description: 'Not otherwise classified (NOC) procedure codes are not covered unless accompanied by supporting documentation', category: 'Documentation' },
  { code: '190', codeType: 'CARC', description: 'Payment is included in the allowance for a Skilled Nursing Facility (SNF) Prospective Payment System (PPS)  claim', category: 'Bundling' },
  { code: '192', codeType: 'CARC', description: 'Non standard adjustment code from an internal system', category: 'Contractual' },
  { code: '193', codeType: 'CARC', description: 'Original payment decision is being maintained. Upon review, it was determined that this claim was processed properly.', category: 'Contractual' },
  { code: '194', codeType: 'CARC', description: 'Anesthesia performed by the operating physician, the assistant surgeon or the attending physician', category: 'Bundling' },
  { code: '195', codeType: 'CARC', description: 'Refund issued to an erroneous priority payer for this claim/service', category: 'Payment' },
  { code: '197', codeType: 'CARC', description: 'Precertification/authorization/notification/pre-treatment absent', category: 'Authorization' },
  { code: '198', codeType: 'CARC', description: 'Precertification/authorization/notification/pre-treatment exceeded', category: 'Authorization' },
  { code: '199', codeType: 'CARC', description: 'Revenue code and Procedure code do not match', category: 'Coding' },
  { code: '200', codeType: 'CARC', description: 'Expenses incurred during lapse in coverage', category: 'Coverage' },
  { code: '201', codeType: 'CARC', description: 'Workers Compensation case settled. Patient is responsible for amount of this claim/service through settlement', category: 'Liability' },
  { code: '202', codeType: 'CARC', description: 'Non-covered personal comfort or convenience services', category: 'Non-Covered' },
  { code: '203', codeType: 'CARC', description: 'Discontinued or reduced service', category: 'Contractual' },
  { code: '204', codeType: 'CARC', description: 'This service/equipment/drug is not covered under the patient\'s current benefit plan', category: 'Non-Covered' },
  { code: '205', codeType: 'CARC', description: 'Pharmacy discount', category: 'Contractual' },
  { code: '206', codeType: 'CARC', description: 'National Provider Identifier - Missing', category: 'Provider' },
  { code: '207', codeType: 'CARC', description: 'National Provider Identifier - Invalid format', category: 'Provider' },
  { code: '208', codeType: 'CARC', description: 'National Provider Identifier - Not matched', category: 'Provider' },
  { code: '209', codeType: 'CARC', description: 'Per regulatory or other agreement, the provider cannot collect this amount from the patient', category: 'Contractual' },
  { code: '210', codeType: 'CARC', description: 'Payment adjusted because pre-certification/authorization not obtained in a timely fashion', category: 'Authorization' },
  { code: '211', codeType: 'CARC', description: 'National Drug Codes (NDC) not covered when submitted as a main billing code', category: 'Coding' },
  { code: '212', codeType: 'CARC', description: 'Service inconsistent with the applicable fee schedule or benefit catalog', category: 'Fee Schedule' },
  { code: '213', codeType: 'CARC', description: 'Payment for this service is included in the reimbursement for a related service', category: 'Bundling' },
  { code: '215', codeType: 'CARC', description: 'Based on subrogation of a third party settlement', category: 'Liability' },
  { code: '216', codeType: 'CARC', description: 'Based on the findings of a review organization', category: 'Medical Necessity' },
  { code: '219', codeType: 'CARC', description: 'Based on extent of injury', category: 'Medical Necessity' },
  { code: '222', codeType: 'CARC', description: 'Exceeds the contracted maximum number of hours/days/units by this provider for this period', category: 'Benefit Limit' },
  { code: '223', codeType: 'CARC', description: 'Adjustment code for mandated federal, state or local law/regulation that is not already covered by another code', category: 'Contractual' },
  { code: '224', codeType: 'CARC', description: 'Patient identification compromised by identity theft. Premium payment credited towards patient\'s account', category: 'Eligibility' },
  { code: '225', codeType: 'CARC', description: 'Penalty or interest payment by the payer for late payment of claim', category: 'Payment' },
  { code: '226', codeType: 'CARC', description: 'Information requested from the Billing/Rendering Provider was not provided or was insufficient/incomplete', category: 'Documentation' },
  { code: '227', codeType: 'CARC', description: 'Information requested from the patient/insured/responsible party was not provided or was insufficient/incomplete', category: 'Documentation' },
  { code: '228', codeType: 'CARC', description: 'Denied for failure of this provider, another provider or spouse/parent/legal guardian to respond to a post-service request for information', category: 'Documentation' },
  { code: '229', codeType: 'CARC', description: 'Partial charge amount not considered by Medicare due to the initial claim was paid under the prospective payment system (PPS)', category: 'Contractual' },
  { code: '231', codeType: 'CARC', description: 'Mutually exclusive procedures cannot be done in the same day/setting', category: 'Bundling' },
  { code: '232', codeType: 'CARC', description: 'Institutional Transfer Amount', category: 'Contractual' },
  { code: '233', codeType: 'CARC', description: 'Services/charges related to the treatment of a hospital-acquired condition or preventable medical error', category: 'Non-Covered' },
  { code: '234', codeType: 'CARC', description: 'This procedure is not paid separately. At least one Remark Code must be provided', category: 'Bundling' },
  { code: '235', codeType: 'CARC', description: 'Sales Tax', category: 'Contractual' },
  { code: '236', codeType: 'CARC', description: 'This procedure or procedure/modifier combination is not compatible with another procedure or procedure/modifier combination provided on the same day', category: 'Bundling' },
  { code: '237', codeType: 'CARC', description: 'Legislative/Regulatory penalty', category: 'Contractual' },
  { code: '238', codeType: 'CARC', description: 'Claim spans ineligible and eligible periods of coverage, this is the reduction for the ineligible period', category: 'Coverage' },
  { code: '239', codeType: 'CARC', description: 'Claim spans a benefit maximum. Charges are not covered for this benefit period', category: 'Benefit Limit' },
  { code: '240', codeType: 'CARC', description: 'Car/van pooling - Loss of transportation has been paid', category: 'Contractual' },
  { code: '241', codeType: 'CARC', description: 'Low Income Subsidy (LIS) co-payment amount', category: 'Patient Responsibility' },
  { code: '242', codeType: 'CARC', description: 'Services not provided by network/primary care providers', category: 'Provider' },
  { code: '243', codeType: 'CARC', description: 'Services not authorized by network/primary care providers', category: 'Authorization' },
  { code: '245', codeType: 'CARC', description: 'Provider performance bonus', category: 'Contractual' },
  { code: '246', codeType: 'CARC', description: 'This non-payable code is for required reporting purposes only', category: 'Contractual' },
  { code: '247', codeType: 'CARC', description: 'Deductible for Catastrophic Coverage', category: 'Patient Responsibility' },
  { code: '248', codeType: 'CARC', description: 'Coinsurance for Catastrophic Coverage', category: 'Patient Responsibility' },
  { code: '249', codeType: 'CARC', description: 'This claim has been identified as a readmission', category: 'Non-Covered' },
  { code: '250', codeType: 'CARC', description: 'The attachment/other documentation referenced on this claim was not received', category: 'Documentation' },
  { code: '251', codeType: 'CARC', description: 'The attachment/documentation referenced is invalid or does not support the claim', category: 'Documentation' },
  { code: '252', codeType: 'CARC', description: 'An attachment/other documentation is required to adjudicate this claim/service', category: 'Documentation' },
  { code: '253', codeType: 'CARC', description: 'Sequestration - Loss of funding', category: 'Contractual' },
  { code: '254', codeType: 'CARC', description: 'Claim received by the dental plan, but benefits not available under this plan. Submit these services to the patient\'s medical plan for processing', category: 'Coverage' },
  { code: '256', codeType: 'CARC', description: 'Service not payable per managed care contract', category: 'Managed Care' },
  { code: '257', codeType: 'CARC', description: 'The disposition of the claim/service is undetermined during the premium payment grace period', category: 'Pending' },
  { code: '258', codeType: 'CARC', description: 'Claim/service not covered when patient is in custody/incarcerated', category: 'Non-Covered' },
  { code: '259', codeType: 'CARC', description: 'Additional payment for Medicaid different rate', category: 'Contractual' },
  { code: '260', codeType: 'CARC', description: 'Claim received by the medical plan, but benefits not available under this plan', category: 'Coverage' },
  { code: '261', codeType: 'CARC', description: 'The procedure or service is inconsistent with the patient\'s history', category: 'Medical Necessity' },
  { code: '262', codeType: 'CARC', description: 'Adjustment for delivery to a service area where a member did not reside', category: 'Coverage' },
  { code: '263', codeType: 'CARC', description: 'Adjustment based on a corrected claim', category: 'Contractual' },
  { code: '264', codeType: 'CARC', description: 'Claim/service adjusted because the payer has recovered a previous overpayment', category: 'Payment' },
  { code: '265', codeType: 'CARC', description: 'Withholding amount to offset prior overpayment', category: 'Payment' },
  { code: '269', codeType: 'CARC', description: 'Charges exceed plan allowance for the claim/service', category: 'Fee Schedule' },
  { code: '270', codeType: 'CARC', description: 'Claim/service denied based on payer terms of benefit', category: 'Non-Covered' },
  { code: '271', codeType: 'CARC', description: 'Services provided during a prior payer coverage period', category: 'Coordination of Benefits' },
  { code: '272', codeType: 'CARC', description: 'Coverage/program guidelines were not met', category: 'Non-Covered' },
  { code: '273', codeType: 'CARC', description: 'Coverage/program guidelines were exceeded', category: 'Benefit Limit' },
  { code: '274', codeType: 'CARC', description: 'Fee/service not payable per patient Care Coordination arrangement', category: 'Managed Care' },
  { code: '275', codeType: 'CARC', description: 'Prior payer\'s (or payers\') patient responsibility (deductible, coinsurance, co-payment) not covered', category: 'Coordination of Benefits' },
  { code: '276', codeType: 'CARC', description: 'Services denied because of federal, state, or local coverage/program guidelines', category: 'Non-Covered' },
  { code: '277', codeType: 'CARC', description: 'Patient financial obligation removed per regulatory requirements', category: 'Contractual' },
  { code: '278', codeType: 'CARC', description: 'Performance program  adjustment', category: 'Contractual' },
  { code: '279', codeType: 'CARC', description: 'Services not provided by a Designated/network provider', category: 'Provider' },
  { code: '280', codeType: 'CARC', description: 'Claim/Service denied/reduced based on federal/state/local regulations', category: 'Non-Covered' },
  { code: '281', codeType: 'CARC', description: 'Deductible waived per contractual agreement', category: 'Contractual' },
  { code: '282', codeType: 'CARC', description: 'The procedure/revenue code is inconsistent with the type of bill', category: 'Coding' },
  { code: '283', codeType: 'CARC', description: 'Adjustment based on a recoupment of a prior payment', category: 'Payment' },
  { code: '284', codeType: 'CARC', description: 'Adjustment based on a payer audit', category: 'Payment' },
  { code: '285', codeType: 'CARC', description: 'Payment denied due to failure to report quality data as required', category: 'Documentation' },
  { code: '286', codeType: 'CARC', description: 'Non covered due to provider contract/plan exclusion', category: 'Non-Covered' },
  { code: '287', codeType: 'CARC', description: 'Adjusted based on modifier associated with procedure/service', category: 'Coding' },
  { code: '288', codeType: 'CARC', description: 'Prior claim/service was reprocessed', category: 'Payment' },

  // ==================== RARC CODES ====================
  { code: 'M1', codeType: 'RARC', description: 'X-ray not taken within the past 12 months or near enough to the start of treatment', category: 'Medical Records' },
  { code: 'M2', codeType: 'RARC', description: 'Not paid separately when the patient is an inpatient', category: 'Bundling' },
  { code: 'M5', codeType: 'RARC', description: 'Information was not sent on a proper HCFA/CMS form', category: 'Documentation' },
  { code: 'M6', codeType: 'RARC', description: 'More than one visit per day is not covered', category: 'Benefit Limit' },
  { code: 'M15', codeType: 'RARC', description: 'Separately billed services/tests have been bundled as they are considered components of the same procedure', category: 'Bundling' },
  { code: 'M20', codeType: 'RARC', description: 'Missing/incomplete/invalid HCPCS', category: 'Coding' },
  { code: 'M24', codeType: 'RARC', description: 'Missing/incomplete/invalid number of units of service', category: 'Documentation' },
  { code: 'M27', codeType: 'RARC', description: 'Only the actual amount charged by the provider for the services may be billed', category: 'Billing' },
  { code: 'M32', codeType: 'RARC', description: 'Alert: This is a conditional payment made pending a decision on this service by the patient\'s primary payer', category: 'Coordination of Benefits' },
  { code: 'M36', codeType: 'RARC', description: 'This claim must be resubmitted with the correct coding/modifier', category: 'Coding' },
  { code: 'M39', codeType: 'RARC', description: 'The provider is not eligible for payment from this payer', category: 'Provider' },
  { code: 'M49', codeType: 'RARC', description: 'Missing/incomplete/invalid value code(s) or amount(s)', category: 'Documentation' },
  { code: 'M50', codeType: 'RARC', description: 'Missing/incomplete/invalid revenue code(s)', category: 'Coding' },
  { code: 'M51', codeType: 'RARC', description: 'Missing/incomplete/invalid procedure code(s)', category: 'Coding' },
  { code: 'M53', codeType: 'RARC', description: 'Missing/incomplete/invalid point of pick-up address', category: 'Documentation' },
  { code: 'M61', codeType: 'RARC', description: 'Missing/incomplete/invalid date of last seen', category: 'Documentation' },
  { code: 'M76', codeType: 'RARC', description: 'Missing/incomplete/invalid diagnosis or condition', category: 'Diagnosis' },
  { code: 'M77', codeType: 'RARC', description: 'Missing/incomplete/invalid place of service', category: 'Place of Service' },
  { code: 'M79', codeType: 'RARC', description: 'Missing/incomplete/invalid charge', category: 'Billing' },
  { code: 'M80', codeType: 'RARC', description: 'Not covered when performed during the same session/date as a previously processed service for that patient', category: 'Duplicate' },
  { code: 'M81', codeType: 'RARC', description: 'You are required to code to the highest level of specificity', category: 'Coding' },
  { code: 'M82', codeType: 'RARC', description: 'Service is not covered when patient is under age 35', category: 'Eligibility' },
  { code: 'M86', codeType: 'RARC', description: 'Service denied because payment already made for same/similar procedure within set time frame', category: 'Duplicate' },
  { code: 'M127', codeType: 'RARC', description: 'Missing/incomplete/invalid operative report', category: 'Documentation' },
  { code: 'M130', codeType: 'RARC', description: 'Record request was made during your claims review process', category: 'Documentation' },
  { code: 'MA04', codeType: 'RARC', description: 'Secondary payment cannot be considered without the identity of or payment information from the primary payer', category: 'Coordination of Benefits' },
  { code: 'MA07', codeType: 'RARC', description: 'The claim information has also been forwarded to Medicaid for review', category: 'Coordination of Benefits' },
  { code: 'MA92', codeType: 'RARC', description: 'Missing plan information for other insurance', category: 'Coordination of Benefits' },
  { code: 'MA130', codeType: 'RARC', description: 'Your claim contains incomplete and/or invalid information', category: 'Documentation' },
  { code: 'N1', codeType: 'RARC', description: 'You may appeal this decision', category: 'Appeal' },
  { code: 'N19', codeType: 'RARC', description: 'Procedure code incidental to primary procedure', category: 'Bundling' },
  { code: 'N20', codeType: 'RARC', description: 'Service not covered when the patient is the provider\'s immediate family member', category: 'Non-Covered' },
  { code: 'N30', codeType: 'RARC', description: 'Missing/incomplete/invalid patient name', category: 'Patient Info' },
  { code: 'N36', codeType: 'RARC', description: 'Claim must meet the primary payer\'s processing requirements before secondary payment can be considered', category: 'Coordination of Benefits' },
  { code: 'N39', codeType: 'RARC', description: 'Procedure code is not compatible with tooth number/letter', category: 'Coding' },
  { code: 'N56', codeType: 'RARC', description: 'Procedure code billed is not correct/valid for the services billed or the date of service billed', category: 'Coding' },
  { code: 'N95', codeType: 'RARC', description: 'This provider type/provider specialty may not bill this service', category: 'Provider' },
  { code: 'N253', codeType: 'RARC', description: 'Missing/incomplete/invalid attending provider primary identifier', category: 'Provider' },
  { code: 'N290', codeType: 'RARC', description: 'Missing/incomplete/invalid diagnosis code', category: 'Diagnosis' },
  { code: 'N362', codeType: 'RARC', description: 'Missing/incomplete/invalid claim information', category: 'Documentation' },
  { code: 'N381', codeType: 'RARC', description: 'Combine related procedures or apply a modifier', category: 'Bundling' },
  { code: 'N386', codeType: 'RARC', description: 'This decision was based on a National Coverage Determination (NCD)', category: 'Coverage Determination' },
  { code: 'N479', codeType: 'RARC', description: 'Missing/Incomplete/Invalid Charge Amount', category: 'Billing' },
  { code: 'N519', codeType: 'RARC', description: 'Missing/incomplete/invalid authorization or referral', category: 'Authorization' },
  { code: 'N595', codeType: 'RARC', description: 'Duplicate claim/service submitted for the same patient', category: 'Duplicate' },
  { code: 'N657', codeType: 'RARC', description: 'This should be billed with the appropriate code for the service/supply provided', category: 'Coding' },
  { code: 'N781', codeType: 'RARC', description: 'Missing/incomplete/invalid NPI or taxonomy', category: 'Provider' },
];
